name: Chocanto

paginate: 3

url: "http://127.0.0.1:4000"

timezone: Europe/Paris

defaults:
    -
     scope:
         path: ""
         type: "posts"
     values:
         author: "Anthony Granger"
         layout: "default"

gems: ["jekyll-paginate"]