name: Chocanto
paginate: 3
url: "http://127.0.0.1:4000"
github-url: "https://github.com/Chocanto/chocanto.me"
github-default-branch: "/edit/master/"

timezone: Europe/Paris

defaults:
    -
     scope:
         path: ""
     values:
         author: "Anthony Granger"
         layout: post
         lang: en
         base-url: "http://127.0.0.1:4000/"
    -
     scope:
         path: fr
     values:
         lang: fr
         base-url: "http://127.0.0.1:4000/fr/"

gems: ["jekyll-paginate"]

langs-value:
    en: ""
    fr: fr

t:
    home:
        en: "home"
        fr: "accueil"
    project:
        en: "project"
        fr: "projets"
    about-me:
        en: "about me"
        fr: "À propos"
    contact:
        en: "contact"
        fr: "contact"
    subtitle:
        en: "My very own part of the Internet"
        fr: "Ma propre partie de l'Internet"