name: Chocanto
paginate: 3
url: "http://127.0.0.1:4000"
github-url: "https://github.com/Chocanto/chocanto.me"
github-default-branch: "/edit/master/"

markdown: redcarpet

timezone: Europe/Paris

defaults:
    -
     scope:
         path: ""
     values:
         author: "Anthony Granger"
         layout: post
         lang: en
         base-url: "http://127.0.0.1:4000/"
         post: true
    -
     scope:
         path: fr
     values:
         lang: fr
         base-url: "http://127.0.0.1:4000/fr/"

gems: ["jekyll-paginate", "github-pages"]

# Value to use into url per language
langs-value:
    en: ""
    fr: fr

# Translation
t:
    home:
        en: "Home"
        fr: "Accueil"
    project:
        en: "Project"
        fr: "Projets"
    about-me:
        en: "About me"
        fr: "À propos"
    contact:
        en: "Contact"
        fr: "Contact"
    subtitle:
        en: "My very own part of the Internet"
        fr: "Ma propre partie de l'Internet"
    footer-article:
        en: "Found a mistake, or just want to add your words to this post ?"
        fr: "Vous avez trouvé une erreur ou souhaitez juste ajouter votre grain de sel ?"
    fork:
        en: "Fork it on github"
        fr: "Éditer sur github"