name: Chocanto
paginate: 3
url: "http://127.0.0.1:4000"
github-url: "https://github.com/Chocanto/chocanto.me"
github-default-branch: "/edit/master/"

timezone: Europe/Paris

defaults:
    -
     scope:
         path: ""
     values:
         author: "Anthony Granger"
         layout: post
         lang: en
         base-url: "http://127.0.0.1:4000/"
    -
     scope:
         path: fr
     values:
         lang: fr
         base-url: "http://127.0.0.1:4000/fr/"

gems: ["jekyll-paginate"]
langs-value:
    en: ""
    fr: fr